apiVersion: apps/v1
kind: Deployment
metadata:
  name: fw-image-deploy
  labels:
    app: fw-image
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fw-image
  template:
    metadata:
      labels:
        app: fw-image
    spec:
      containers:
        - name: fw-image
          image: 34.22.80.2:30110/fw-image:test   # ⬅️ 아까 빌드해서 Nexus에 push한 이미지
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
      # (필요하다면) imagePullSecrets:
      #   - name: nexus-registry-secret
