apiVersion: apps/v1
kind: Deployment
metadata:
  name: fw-image-deploy
  labels:
    app: fw-images
spec:
  revisionHistoryLimit: 3
  replicas: 5
  selector:
    matchLabels:
      app: fw-images
  template:
    metadata:
      labels:
        app: fw-images
    spec:
      containers:
        - name: fw-images
          image: 34.64.159.32:30110/fw-images:bc29f8d
          imagePullPolicy: Always
          ports:
            - containerPort: 80
      # (필요하다면) imagePullSecrets:
      #   - name: nexus-registry-secret
