apiVersion: v1
kind: Service
metadata:
  name: fw-image-svc
spec:
  type: NodePort
  selector:
    app: fw-images
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080
  # type: ClusterIP
